name             'lazy_brigade'
maintainer       'Eugene Hlyzov'
maintainer_email 'hlyzov@gmail.com'
license          'MIT'
description      'These guys can do some rails, but do not expect too much'
version          '1.0.0'

depends          'sudo'
depends          'nginx'
depends          'runit'
